name: Build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Get the sources
      uses: actions/checkout@v1
    - name: Run the build
      run: powershell.exe -File build.ps1
