name: Build

on: [push]

jobs:
  tests:
    runs-on: windows-latest

    steps:
    - name: Get the sources
      uses: actions/checkout@v1
    - name: Run tests
      run: build.bat Test
  
  build:
    needs: tests
    runs-on: windows-latest

    steps:
    - name: Get the sources
      uses: actions/checkout@v1
    - name: Run the build
      run: build.bat
